name: cafe_analog_app
description: A coffeecard app for Caf√© Analog.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.8
  flutter: 3.38.9

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^17.1.0
  intl: ^0.20.2
  chopper: ^8.0.3 # swagger generator
  json_annotation: ^4.9.0 # swagger generator
  fpdart: ^1.1.1
  logger: ^2.6.2
  equatable: ^2.0.7
  gap: ^3.0.1
  dotted_border: ^3.1.0
  flutter_secure_storage: ^10.0.0
  collection: ^1.19.1
  shared_preferences: ^2.5.4

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0
  build_runner: ^2.11.0 # swagger generator
  chopper_generator: ^8.6.0 # swagger generator
  json_serializable: ^6.8.0 # swagger generator
  swagger_dart_code_generator: ^4.1.1 # swagger generator
  build_verify: ^3.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
