name: router_test_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.1
  intl: ^0.20.2
  chopper: ^8.0.3 # swagger generator
  json_annotation: ^4.9.0 # swagger generator
  fpdart: ^1.1.1
  logger: ^2.6.2
  equatable: ^2.0.7

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  build_runner: ^2.4.9 # swagger generator
  chopper_generator: ^8.0.3 # swagger generator
  json_serializable: ^6.8.0 # swagger generator
  swagger_dart_code_generator: ^3.0.1 # swagger generator

flutter:
  generate: true
  uses-material-design: true
